# Generated by Django 5.0.6 on 2024-11-16 18:08

import django.db.models.deletion
from django.db import migrations, models

def create_or_update_site(apps, schema_editor):
    # Get the Site model from the historical version of the app registry
    Site = apps.get_model('sites', 'Site')
    Site.objects.update_or_create(
        id=1,  # Ensure this matches the default site ID
        defaults={
            'domain': 'localhost:8000',  # Replace with your domain if necessary
            'name': 'Localhost'  # Replace with the name of your site if necessary
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audience_criteria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.customer')),
            ],
        ),
    ]
